#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'highestValuePalindrome' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER n
#  3. INTEGER k
#

def highestValuePalindrome(s, n, k):
    # Write your code here
    s = list(s)
    radius = n // 2
    odd = n % 2 != 0
    diffPos = [2 if s[i] == s[n-i-1] else 1 for i in range(0,radius)]
    unequal = [i for i in range(len(diffPos)) if diffPos[i] == 1]
    
    if len(unequal) > k:
        return '-1'
    
    #sawp all unequal
    k = k-len(unequal)
    for i in unequal:
        max_val = max(s[i], s[n-i-1])
        s[i] = s[n-i-1] = max_val
        
    for i in range(n):
        if k == 0:
            break
        if s[i] == '9':
            continue
        if i in unequal:
            s[i] = s[n-i-1] = '9'
            k -= 1 
        elif k >= 2:
            s[i] = s[n-i-1] = '9'
            k -= 2
    
    if k > 0 and odd:
        s[radius] = '9'
    
    return ''.join(s)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    s = input()

    result = highestValuePalindrome(s, n, k)

    fptr.write(result + '\n')

    fptr.close()
